### ISSUE TITLE
[BUG] Development - Can't start docker container

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/common-voice#4003]
**Describe the bug**
I tried to set up CV locally from a fresh setup on Fedora. Building the docker container works, however when it comes to running it, the command (from `docker-compose.yml`) `bash -c "/code/docker/wait-for-it.sh s3proxy:80 -- /code/docker/prepare_s3.sh && yarn && yarn start"` fails due to:

```
~/development/common-voice main ⇡ ❯ docker-compose up -d && docker logs -f web
redis is up-to-date
s3proxy is up-to-date
db is up-to-date
Recreating web ... done
bash: /code/docker/wait-for-it.sh: Permission denied
```

The issue here seems to be that, when mounted through the volume in docker-compose.yml, the owner user/group is wrong:

```
drwxr-xr-x.   1 root root  160 Apr 15 17:26 .
drwxr-xr-x.   1 root root  160 Apr 15 17:26 ..
-rwxr-xr-x.   1 root root    0 Apr 15 17:26 .dockerenv
drwxr-xr-x.   1 root root  948 Apr 20  2022 bin
drwxr-xr-x.   1 root root    0 Jul 10  2020 boot
drwxr-xr-x.   1 node node  670 Apr 15 08:00 code
drwxr-xr-x.   5 root root  340 Apr 15 17:26 dev
drwxr-xr-x.   1 root root 1848 Apr 15 17:26 etc
drwxr-xr-x.   1 root root    8 Apr 20  2022 home
drwxr-xr-x.   1 root root   90 Apr 20  2022 lib
drwxr-xr-x.   1 root root   40 Apr 18  2022 lib64
drwxr-xr-x.   1 root root    0 Apr 18  2022 media
drwxr-xr-x.   1 root root    0 Apr 18  2022 mnt
drwxr-xr-x.   1 root root   26 Apr 20  2022 opt
dr-xr-xr-x. 483 root root    0 Apr 15 17:26 proc
drwx------.   1 root root   42 Apr 20  2022 root
drwxr-xr-x.   1 root root   16 Apr 18  2022 run
drwxr-xr-x.   1 root root 1084 Apr 20  2022 sbin
drwxr-xr-x.   1 root root    0 Apr 18  2022 srv
dr-xr-xr-x.  13 root root    0 Apr 15 07:56 sys
drwxrwxrwt.   1 root root  954 Apr 15 17:20 tmp
drwxr-xr-x.   1 root root   70 Apr 18  2022 usr
drwxr-xr-x.   1 root root   90 Apr 18  2022 var
ls: cannot open directory '/code': Permission denied
```

The container itself is correctly run as `app` user and the GUID/UID are correct as well.

Running the container without docker-compose works and the permissions for `/code` are correct. This can be verified by removing the `volume` definition in `docker-compose.yml`.

**Comment by moz-dfeller** [comment]
Good catch, thank you! Must be related to the recent change in #3999

**Comment by Flipez** [comment]
Hi @MichaelKohler,

Could you try to modify the compose file with your local UID und GID like this:

```
  app:
    build:
      context: .
      args:
        UID: 0
        GID: 0
```

and rebuild the image to see if it works? We currently set 10001:10001 if no argument is provided but for local development you want the code to be available for your local user.

**Comment by MichaelKohler** [comment]
@Flipez Do you have another idea?

**Comment by MichaelKohler** [comment]
@moz-dfeller do you have any other idea here?

**Comment by Rebreda** [comment]
@MichaelKohler I also had a permission related issue (although mine was related to yarn being unable to write to `/code/.cache/yarn` or even the error log at `/code/yarn-error.log`. 

I'd guess because I already had run docker compose as sudo before the Dockerfile changes things weren't adding up permission-wise. I tried deleting all CV related containers/images/volumes etc and rebuilding but that didn't work. I then modified the docker-compose file by creating a new volume like below:
```yaml
...
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: web
    links:
      - db
      - redis
    volumes:
      - cv-data:/code
    environment:
      - DOTENV_CONFIG_PATH=/code/.env-local-docker
    networks:
      - voice-web
    ports:
      - 9000:9000
    command: bash -c "/code/docker/wait-for-it.sh s3proxy:80 -- /code/docker/prepare_s3.sh && yarn && yarn start"

networks:
  voice-web:
volumes:
  cv-data:
```

And rebuilt (it would result in all local data being removed) and it worked (on PopOS/Linux).
