### ISSUE TITLE
[BUG] Small css change required for translations fit the new Write page

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#4071]
**Describe the bug**
Some translations might be longer than English counterparts, e.g. Turkish is 15% longer on average. That resulted in an overflow on the right side.

**Screenshots**
![image](https://github.com/common-voice/common-voice/assets/8849617/65a71e2d-1fcb-4606-a6c3-7a9d5ebde3ad)

**Expected behavior**

**Desktop or Mobile (please complete the following information):**
 - Desktop larger screen

**Additional context**
This is the css rule which can be modified from
```css
.rules ul li {
  margin-bottom: 16px;
  width: 250px;
}
```
to:
```css
.rules ul li {
  margin-bottom: 12px;
  width: 250px;
}
```
for fixing the issue.

Allowing a 15-20% slack in the English design or making the sizes adaptive can help in the future.
